# Build and deploy Python project to Azure Function App - AdeemyAnalytics

name: Build and deploy Python project to Azure Function App - AdeemyAnalytics

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'  # Set this to the path to your web app project, defaults to the repository root
  PYTHON_VERSION: '3.10'  # Python version to use

permissions:
    id-token: write  # Required for OpenID Connect (OIDC)
    contents: read  # Additional read permissions for the repository

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python version
        uses: actions/setup-python@v5 
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: pip install -r requirements.txt

      # Optional: Add step to run tests here if you have tests for your project

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r -x 'venv/*' '.git/*' '.github/*'

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            release.zip
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app
          path: ./artifact  # Especificamos un directorio para el artefacto

      - name: Login to Azure using OpenID Connect (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to Azure Functions
        uses: Azure/functions-action@v1
        id: deploy-to-function
        with:
          app-name: 'AdeemyAnalytics'
          slot-name: 'Production'
          package: './artifact/release.zip'
          scm-do-build-during-deployment: true
          enable-oryx-build: true

      - name: Clean up artifacts (optional)
        run: rm -f release.zip
