# .github/workflows/main_adeemyanalytics.yml

name: Build and deploy Python project to Azure Function App - AdeemyAnalytics

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'  # Ruta al proyecto
  PYTHON_VERSION: '3.10'  # Versión de Python

permissions:
  id-token: write  # Requerido para OIDC
  contents: read  # Permisos adicionales de lectura

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python version
        uses: actions/setup-python@v5 
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Setup and install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      # Opcional: Añadir paso para ejecutar tests

      - name: Zip artifact for deployment
        run: zip -r release.zip ./* -x 'venv/*' '.git/*' '.github/*'

      - name: List ZIP contents
        run: unzip -l release.zip

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app
          path: ./artifact  # Especificamos un directorio para el artefacto

      - name: Login to Azure using OpenID Connect (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to Azure Functions
        uses: Azure/functions-action@v2  # Actualizado a v2
        with:
          app-name: 'AdeemyAnalytics'
          slot-name: 'Production'
          package: './artifact/release.zip'
          scm-do-build-during-deployment: false
          enable-oryx-build: false

      - name: Clean up artifacts (optional)
        run: rm -f release.zip
